### ISSUE TITLE
get "oldest" peers?

### ISSUE THREAD

**Issue by mafintosh** [tristanls/k-bucket#40]
is there an api to get n "oldest" peers in term of time they were last added? basically similar to the peers emitted in the ping event.

my use-case is that i want to ping old peers once in a while to see if they are still alive.

**Comment by fanatid** [comment]
@mafintosh "oldest" should include removed from k-bucket? what about `toArray`?

**Comment by mafintosh** [comment]
toArray returns all nodes right? I was wanna get `n` nodes that was least recently added. I assume you have an index of that since `ping` event emits an array of nodes that was least recently added as well but I could of course be mistaken about this.

**Comment by fanatid** [comment]
yes, toArray returns all nodes
k-bucket store peers in addition order, but in a few arrays, so we can not say for sure what peers in nodes oldest and which is newest
why not save peers in array from event `added`?

**Comment by mafintosh** [comment]
sure, i can easily maintain a list myself.

**Comment by tristanls** [comment]
As both of you already mentioned, we have a sort of mixed way of retrieving nodes. They are stored in "most recently contacted" order per bucket (https://github.com/tristanls/k-bucket/blob/5ab987935944314cd0b61d3df9e6dd5e7aade3f2/index.js#L304-L305), but there is no global "most recently contacted" order.

Another way that might make maintenance of this data easier is to provide it as satellite data to the `contact` object. That is, if what we care about is when the `contact` was added in "wall-clock" time (as opposed to the relative ordering of how recently we contacted it), perhaps including a `contact.createTimestamp` field when inserting.

Since the entire `contact` event is emitted on `ping`, when you do the ping work, it is possible to update `contact.lastPingTimestamp` field prior to calling `kBucket.add(contact)`. 

This way, when you want to ping some nodes you haven't in a while, the array returned by `toArray` can be sorted according to the desired criteria, either by `contact.createTimestamp`, `contact.lastPingTimestamp`, or some variation thereof.

I know this is a version of maintaining a list yourself, but perhaps this is a more convenient approach?

**Comment by tristanls** [comment]
On the other hand, since there is already a bunch of maintenance work happening when contacts are added and pinged, maintaining another data structure that provides a global "most recently contacted" (so conversely, "oldest") nodes would consist of a `splice` and a `push` onto this global "most recently contacted" array somewhere around here https://github.com/tristanls/k-bucket/blob/5ab987935944314cd0b61d3df9e6dd5e7aade3f2/index.js#L115

**Comment by tristanls** [comment]
Closing since it's been a while 🙂 and looks like no further activity on this.
